"""add destination_field to mappingbindingsignoff"""

from alembic import op
import sqlalchemy as sa


revision = '460c9261a905'
down_revision = '0035'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('mapping_binding_sign_offs', sa.Column('destination_field', sa.String(length=128), nullable=False, server_default=''))
    op.alter_column('mapping_binding_sign_offs', 'destination_object_name', type_=sa.String(length=128), existing_type=sa.String(length=255))
    op.alter_column('mapping_binding_sign_offs', 'source_field', type_=sa.String(length=128), existing_type=sa.String(length=255))
    # op.drop_constraint('uq_mapping_binding_sign_off', 'mapping_binding_sign_offs', type_='unique')
    op.create_unique_constraint('uq_mapping_binding_sign_off', 'mapping_binding_sign_offs', ['mapping_snapshot_id', 'destination_object_name', 'source_field', 'destination_field', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_mapping_binding_sign_off', 'mapping_binding_sign_offs', type_='unique')
    op.create_unique_constraint('uq_mapping_binding_sign_off', 'mapping_binding_sign_offs', ['mapping_snapshot_id', 'destination_object_name', 'source_field', 'user_id'])
    op.alter_column('mapping_binding_sign_offs', 'source_field', type_=sa.String(length=255), existing_type=sa.String(length=128))
    op.alter_column('mapping_binding_sign_offs', 'destination_object_name', type_=sa.String(length=255), existing_type=sa.String(length=128))
    op.drop_column('mapping_binding_sign_offs', 'destination_field')
    # ### end Alembic commands ###


